from .age import *  # type: ignore
from .animal import *  # type: ignore
from .answer import *  # type: ignore
from .aqi import *  # type: ignore
from .aws import *  # type: ignore
from .book import *  # type: ignore
from .calc import *  # type: ignore
from .closers import *  # type: ignore
from .core import *  # type: ignore
from .dday import *  # type: ignore
from .dic import *  # type: ignore
from .dns import *  # type: ignore
from .exchange import *  # type: ignore
from .help import *  # type: ignore
from .hi import *  # type: ignore
from .loading import *  # type: ignore
from .memo import *  # type: ignore
from .nyaa import *  # type: ignore
from .ping import *  # type: ignore
from .pongdang import *  # type: ignore
from .quit import *  # type: ignore
from .ref import *  # type: ignore
from .saomd import *  # type: ignore
from .select import *  # type: ignore
from .sub import *  # type: ignore
from .subscribe import *  # type: ignore
from .subway import *  # type: ignore
