from .aws import *  # type: ignore
from .calc import *  # type: ignore
from .core import *  # type: ignore
from .exchange import *  # type: ignore
from .help import *  # type: ignore
from .hi import *  # type: ignore
from .nyaa import *  # type: ignore
from .ping import *  # type: ignore
from .quit import *  # type: ignore
from .saomd import *  # type: ignore
from .select import *  # type: ignore
from .sub import *  # type: ignore
from .subway import *  # type: ignore
from .test import *  # type: ignore
