services:
  db:
    image: postgres:16
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=DEV_ONLY
      - TZ=UTC
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
