services:
  bot_item4:
    image: ghcr.io/item4/yui:latest
    volumes:
      - ./item4:/yui/data
    environment:
      - YUI_CONFIG_FILE_PATH=data/yui.config.toml
    depends_on:
      - db
      - valkey
    links:
      - db
      - valkey
    command: ./data/run.sh
    networks:
      yuinet:
        ipv4_address: 10.5.0.101
  db:
    image: postgres:16
    volumes:
      - ./postgres@16data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=MYSECRET
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      yuinet:
        ipv4_address: 10.5.0.2
  valkey:
    image: valkey/valkey:latest
    networks:
      yuinet:
        ipv4_address: 10.5.0.4

networks:
  yuinet:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
