TOKEN = 'YOUR_TOKEN_HERE'

PREFIX = '.'

APPS = [
    # Core apps
    'yui.apps.core',

    # Root apps
    'yui.apps.animal',
    'yui.apps.hi',
    'yui.apps.ping',

    # Compute apps
    'yui.apps.compute.calc',
    'yui.apps.compute.exchange',
    'yui.apps.compute.gacha',
    'yui.apps.compute.gamble',
    'yui.apps.compute.select',
    'yui.apps.compute.translate',

    # Date apps
    'yui.apps.date.age',
    'yui.apps.date.day',
    'yui.apps.date.dday',
    'yui.apps.date.monday',
    'yui.apps.date.weekend',
    'yui.apps.date.work',

    # Funny apps
    'yui.apps.fun.answer',
    'yui.apps.fun.code',
    'yui.apps.fun.hassan',
    'yui.apps.fun.relax',

    # Info apps
    'yui.apps.info.memo',
    'yui.apps.info.about',
    'yui.apps.info.help',
    'yui.apps.info.packtpub.commands',
    'yui.apps.info.packtpub.tasks',

    # Search apps
    'yui.apps.search.book',
    'yui.apps.search.dic',
    'yui.apps.search.dns',
    'yui.apps.search.nyaa',
    'yui.apps.search.ref',
    'yui.apps.search.sub',
    'yui.apps.search.subway',

    # Weather apps
    'yui.apps.weather.weather',
]

DATABASE_URL = 'postgresql://postgres:MYSECRET@db/dbname'
DATABASE_ECHO = false

NAVER_CLIENT_ID = 'NAVER_CLIENT_ID'
NAVER_CLIENT_SECRET = 'NAVER_CLIENT_SECRET'

GOOGLE_API_KEY = 'GOOGLE_API_KEY'

OPENWEATHER_API_KEY = 'OPENWEATHER_API_TOKEN'

WEBSOCKETDEBUGGERURL = 'http://10.5.0.3:9222/json/version'

[CHANNELS]
general = 'C1111'
game = 'C2222'
game_and_test = ['C2222', 'C3333']
welcome = 'C1111'

[USERS]
owner = 'U11111111'

[CACHE]
HOST = 'memcached'
PORT = 11211
PREFIX = 'YUI_'

[LOGGING]
version = 1
disable_existing_loggers = false

[LOGGING.formatters.brief]
format = '%(message)s'

[LOGGING.formatters.default]
format = '%(asctime)s %(levelname)s %(name)s %(message)s'
datefmt = '%Y-%m-%d %H:%M:%S'

[LOGGING.handlers.console]
class = 'logging.StreamHandler'
formatter = 'default'
level = 'DEBUG'
filters = []
stream = 'ext://sys.stdout'

[LOGGING.handlers.file]
class = 'logging.handlers.RotatingFileHandler'
formatter = 'default'
level = 'WARNING'
filename = 'log/warning.log'
maxBytes = 102400
backupCount = 3

[LOGGING.loggers.yui]
handlers = ['console', 'file']
propagate = true
level = 'DEBUG'
