TOKEN = 'YOUR_TOKEN_HERE'

PREFIX = '.'

APPS = [
    # Core apps
    'yui.apps.core',

    # Shared Models
    'yui.apps.shared',

    # Root apps
    'yui.apps.animal',
    'yui.apps.hi',
    'yui.apps.ping',
    'yui.apps.quit',

    # Compute apps
    'yui.apps.compute.calc',
    'yui.apps.compute.exchange',
    'yui.apps.compute.gacha',
    'yui.apps.compute.gamble',
    'yui.apps.compute.select',

    # Date apps
    'yui.apps.date.age',
    'yui.apps.date.day',
    'yui.apps.date.dday',
    'yui.apps.date.monday',
    'yui.apps.date.weekend',

    # Funny apps
    'yui.apps.fun.answer',
    'yui.apps.fun.hassan',
    'yui.apps.fun.relax',

    # Info apps
    'yui.apps.info.memo',
    'yui.apps.info.saomd',
    'yui.apps.info.subscribe',
    'yui.apps.info.about',
    'yui.apps.info.help',
    'yui.apps.info.packtpub',

    # Search apps
    'yui.apps.search.book',
    'yui.apps.search.dic',
    'yui.apps.search.dns',
    'yui.apps.search.nyaa',
    'yui.apps.search.ref',
    'yui.apps.search.sub',
    'yui.apps.search.subway',

    # Weather apps
    'yui.apps.weather.aws',
    'yui.apps.weather.aqi',
    'yui.apps.weather.pongdang',
]

OWNER_ID = 'U11111111'

DATABASE_URL = 'postgresql://postgres:MYSECRET@db/dbname'
DATABASE_ECHO = false

NAVER_CLIENT_ID = 'NAVER_CLIENT_ID'
NAVER_CLIENT_SECRET = 'NAVER_CLIENT_SECRET'

GOOGLE_API_KEY = 'GOOGLE_API_KEY'

AQI_API_TOKEN = 'AQI_API_TOKEN'

WEBSOCKETDEBUGGERURL = 'http://10.5.0.2:9222/json/version'

TDCPROJECT_KEY = 'TDCPROJECT_KEY'

[CHANNELS]
general = '_general'
game = 'game'
game_and_test = ['game', 'test']
welcome = '_general'

[LOGGING]
version = 1
disable_existing_loggers = false

[LOGGING.formatters.brief]
format = '%(message)s'

[LOGGING.formatters.default]
format = '%(asctime)s %(levelname)s %(name)s %(message)s'
datefmt = '%Y-%m-%d %H:%M:%S'

[LOGGING.handlers.console]
class = 'logging.StreamHandler'
formatter = 'default'
level = 'DEBUG'
filters = []
stream = 'ext://sys.stdout'

[LOGGING.handlers.file]
class = 'logging.handlers.RotatingFileHandler'
formatter = 'default'
level = 'WARNING'
filename = 'log/warning.log'
maxBytes = 102400
backupCount = 3

[LOGGING.loggers.yui]
handlers = ['console', 'file']
propagate = true
level = 'DEBUG'
